# docker-compose.yaml
version: '3'
services:
 jenkins:
  image: jenkinsci/blueocean:latest
  container_name: jenkins
  ports:
   - 8080:8080
 volumes:
  - /home/jenkins/jenkins_home:/var/jenkins_home
  - /var/run/docker.sock:/var/run/docker.sock
 restart: on-failure